import { useState, useEffect } from 'react';

/**
 * Reusable Panel to load and display AI insights (Explanation, Critique, Summary, etc.)
 * @param {string} title The title to show on the card header
 * @param {string} icon Emoji icon for the card
 * @param {function} fetchFn The API function that returns { text: string }
 * @param {object} args The arguments required for fetchFn (e.g., workerData)
 * @param {boolean} trigger Refetch trigger token (to manually refetch when props update)
 */
export default function AIPanel({ title = "AI Insights", icon = "✨", fetchFn, args, trigger }) {
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState(null);
    const [error, setError] = useState(false);

    useEffect(() => {
        if (!fetchFn || !args) return;
        
        // Don't refetch if args hasn't valid data structure (or trigger empty)
        let mounted = true;
        setLoading(true);
        setError(false);
        setResult(null);

        fetchFn(...args).then(res => {
            if (mounted) {
                setResult(res.text);
                setLoading(false);
            }
        }).catch(err => {
            if (mounted) {
                console.error("AI Fetch Error:", err);
                setError(true);
                setLoading(false);
            }
        });

        return () => { mounted = false; };
    }, [fetchFn, trigger]); // Only refetch when trigger changes

    return (
        <div className="card ai-panel">
            <div className="card-header">
                <span className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    {icon} {title}
                </span>
                <span className="ai-badge">AI Assistant</span>
            </div>
            <div className="ai-content">
                {loading && (
                    <div className="ai-loader">
                        <div className="spinner" style={{ width: '20px', height: '20px', borderWidth: '2px' }} />
                        <span style={{ fontSize: '13px', color: 'var(--text-muted)' }}>Analyzing data...</span>
                    </div>
                )}
                
                {error && !loading && (
                    <div style={{ color: 'var(--risk-high)', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '4px' }}>
                        <span>⚠</span> AI Service is currently unavailable.
                    </div>
                )}

                {!loading && !error && result && (
                    <div className="ai-text markdown-body">
                        {/* A very crude markdown renderer for lists/bold text the AI might return */}
                        {result.split('\n').map((line, i) => {
                            let cleanLine = line.replace(/\*\*(.*?)\*\*/g, '<b>$1</b>');
                            if (line.startsWith('* ') || line.startsWith('- ')) {
                                return <li key={i} dangerouslySetInnerHTML={{ __html: cleanLine.substring(2) }} />;
                            } else if (line.trim() === '') {
                                return <br key={i} />
                            }
                            return <p key={i} dangerouslySetInnerHTML={{ __html: cleanLine }} />;
                        })}
                    </div>
                )}
                {!loading && !error && !result && (
                    <span style={{ color: 'var(--text-muted)', fontSize: '13px' }}>Waiting for data...</span>
                )}
            </div>
            <div className="ai-disclaimer">
                This analysis is generated by AI to support decision-making, it does not recalculate the numerical score.
            </div>
        </div>
    );
}
